### ISSUE TITLE
Erreur lors de l'install

### ISSUE THREAD

**Issue by hugoperier** [remicaumette/dofus-touch-bot#1]
Impossible d'installer le bot

Je suis sur ubuntu 16

[npm-debug.log](https://github.com/remicaumette/dofus-touch-bot/files/1759723/npm-debug.log)

**Comment by remicaumette** [comment]
Salut, je te répond que maintenant car j'ai pas les notifs GitHub (wtf). Sinon essaye de mettre à jour nodejs et npm. T'as bien fait toute l'installation ?
```
npm install
npm run build
npm start
```
Si t'as d'autre question n'hésite pas 😄

**Comment by hugoperier** [comment]
Yo, j'ai reussi a l'install sur le pc d'un pote (Mon ubuntu met pas a jour nodejs plus haut que v4.2.6 xD) et on peux que se co.


C'est un bug ou c'est pas plus dev que ca ?


Hugo PERIER

Lyon Promo 2021

Epitech

06.01.44.21.30

________________________________
De : Rémi Caumette <notifications@github.com>
Envoyé : mercredi 14 mars 2018 19:34:02
À : remicaumette/dofus-touch-bot
Cc : hugo perier; Author
Objet : Re: [remicaumette/dofus-touch-bot] Erreur lors de l'install (#1)


Salut, je te répond que maintenant car j'ai pas les notifs GitHub (wtf). Sinon essaye de mettre à jour nodejs et npm. T'as bien fait toute l'installation ?

npm install
npm run build
npm start


Si t'as d'autre question n'hésite pas :)

**Comment by remicaumette** [comment]
Concrètement, on peut uniquement se connecter, cependant j'ai créé toute l'abstraction nécessaire pour faire un bot. Pour ton installation de nodejs tu peux suivre ce tutoriel : https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions .
